using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Clase HeroMovement para definir el movimiento del objeto Hero
public class HeroMovement : MonoBehaviour
{

    // mousePosition: variable para definir la posici칩n vectorial del mouse
    Vector3 mousePosition;

    // movementSpeed: variable para definir la velocidad de movimiento del heroe
    public float movementSpeed = 4;

    void Start()
    {
        
    }

    void Update()
    {
        // Si no se ha perdido y el juego no est치 pausado, realizar l칩gica de movimiento
        // del heroe. El heroe se mueve verticalmente siguiendo la posici칩n Y del mouse.
        if (!GameManager.Instance.stopped && !GameManager.Instance.lost) {
            mousePosition = Camera.main.ScreenToWorldPoint(Input.mousePosition);
            mousePosition.z = transform.position.z;
            mousePosition.x = transform.position.x;
            transform.position = Vector3.MoveTowards(transform.position, mousePosition, movementSpeed*Time.deltaTime);
        }
    }
}
